[package]
name = "ayysee-wasm"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
ayysee-compiler = { path = "../compiler" }
ayysee-parser = { path = "../parser" }
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
